export const services = [
  { slug:'customer-support', es:'automatizacion-atencion-cliente', title:'Customer support', headline:'Every customer question deserves a clear next step.', description:'Connect incoming messages, prepare useful responses, and route exceptions to the right person. Your team keeps control of what gets sent.', service:'customer_service_automation', cluster:'customer_service', examples:[['Sort the inbox','Classify questions by topic, urgency, and the team responsible.'],['Prepare a response','Draft answers using an approved knowledge base and the context available.'],['Keep people in the loop','Route sensitive, incomplete, or unusual requests for human review.'],['Record the outcome','Update the customer record so the next conversation starts with context.']], deliverables:['An inventory of channels, frequent questions, and escalation rules.','An approved knowledge base and a defined tone of voice.','A workflow connected to the agreed inbox, messaging channel, or CRM.','Human review, fallback paths, and a record of important actions.','Tests with normal, incomplete, and exceptional cases.','Documentation and training for the person who will own the workflow.'], measure:'Response time, correctly routed questions, draft acceptance, and cases that require human intervention.', limit:'A draft is not an approved response. Sensitive cases and decisions with significant consequences require explicit human oversight.' },
  { slug:'sales', es:'automatizacion-ventas', title:'Sales & follow-up', headline:'Give every opportunity a next step.', description:'Connect forms to your CRM, apply agreed qualification rules, and prepare timely follow-up. Your team gets better context and keeps the commercial decision.', service:'sales_automation', cluster:'sales', examples:[['Capture once','Bring leads from forms and approved channels into one consistent record.'],['Qualify with context','Apply explicit criteria and show why an opportunity has a given priority.'],['Keep the CRM useful','Create or update contacts with ownership, source, and duplicate checks.'],['Follow up on time','Prepare approved messages and reminders when an opportunity needs attention.']], deliverables:['A map of the sales process and where opportunities lose momentum.','Agreed fields, qualification criteria, and responsibilities.','A workflow connecting the agreed forms, CRM, and channels.','Rules for assignment, duplicates, consent, and exceptions.','Follow-up sequences or drafts reviewed by the team.','Tests, documentation, a simple monitoring view, and handover.'], measure:'Time to first contact, leads with a next step, complete records, duplicates, and opportunities without follow-up.', limit:'Qualification supports a commercial decision. It must not invent customer data, ignore consent, or send unapproved outreach.' },
  { slug:'operations', es:'automatizacion-procesos', title:'Operations', headline:'Less copying between tools. More reliable work.', description:'Move information between documents, email, spreadsheets, and internal tools. Validate the data, surface exceptions, and keep a clear record of what happened.', service:'process_automation', cluster:'operations', examples:[['Read incoming documents','Extract agreed fields and identify missing or inconsistent information.'],['Connect the tools','Move validated information between the applications your team already uses.'],['Surface exceptions','Stop and ask for review when a record does not meet the agreed rules.'],['Make progress visible','Create useful internal reports and alerts with an audit trail.']], deliverables:['A process map with inputs, outputs, owners, and dependencies.','Defined data fields, validation rules, and access requirements.','Connections between the tools included in the scope.','Exception handling, alerts, and a safe manual fallback.','Tests using representative real-world cases.','Operating documentation, training, and an agreed handover.'], measure:'Manual interventions, processing time, validation errors, and successfully completed records.', limit:'Automation must not approve payments, change sensitive records, or make high-impact decisions without the controls agreed for the process.' },
] as const;
export const phases = [
 ['Understand','Review the process, frequency, tools, data, and risk. Identify one useful first outcome.'],
 ['Design','Define inputs, outputs, owners, exceptions, and what a successful result looks like.'],
 ['Build','Connect the workflow in stages and keep a record of key decisions.'],
 ['Test','Try normal, incomplete, and incorrect inputs. Check failure paths as carefully as the happy path.'],
 ['Hand over','Document the system, train its owner, and launch with monitoring and a manual fallback.'],
 ['Improve','Review incidents and measurements before extending the scope.'],
];
export const serviceFaq = [
 ['Who is this for?','Small businesses and independent professionals with a recurring process, an internal owner, and access to the tools involved.'],
 ['Can we keep our current tools?','Usually, if they offer a suitable API, webhook, or export. We check permissions and limitations before committing to a connection.'],
 ['How long does it take?','A scoped implementation typically takes two to four weeks. Several integrations may take four to eight weeks. Timing is confirmed after reviewing access, scope, and capacity.'],
 ['Will AI replace human review?','We agree where automation can act and where a person must decide. Sensitive data, unusual cases, and high-impact decisions need appropriate oversight.'],
 ['Can we start with one process?','Yes. Start with a bounded workflow and a measurable outcome, then expand when the first version is working reliably.'],
];
